const exploreProducts = [
  {
    name: "Breed Dry Dog Food",
    price: 100,
    rating: 4,
    reviews: 35,
    isNew: false,
    colors: [],
    image: "Product1.png",
  },
  {
    name: "CANON EOS DSLR Camera",
    price: 360,
    rating: 4,
    reviews: 95,
    isNew: false,
    colors: [],
    image: "Product2.png",
  },
  {
    name: "ASUS FHD Gaming Laptop",
    price: 700,
    rating: 5,
    reviews: 325,
    isNew: false,
    colors: [],
    image: "Product3.png",
  },
  {
    name: "Curology Product Set",
    price: 500,
    rating: 4,
    reviews: 145,
    isNew: false,
    colors: [],
    image: "Product6.png",
  },
  {
    name: "Kids Electric Car",
    price: 960,
    rating: 5,
    reviews: 65,
    isNew: true,
    colors: ["#DB4444", "#DB4444"],
    image: "Product5.png",
  },
  {
    name: "Jr. Zoom Soccer Cleats",
    price: 1160,
    rating: 5,
    reviews: 35,
    isNew: false,
    colors: ["#FFEB3B", "#DB4444"],
    image: "Product6.png",
  },
  {
    name: "GP11 Shooter USB Gamepad",
    price: 660,
    rating: 4,
    reviews: 55,
    isNew: true,
    colors: ["#000000", "#DB4444"],
    image: "Product7.png",
  },
  {
    name: "Quilted Satin Jacket",
    price: 660,
    rating: 4,
    reviews: 55,
    isNew: false,
    colors: ["#4B5563", "#DB4444"],
    image: "Product8.png",
  },
]

export default exploreProducts